-- 1. users
CREATE TABLE IF NOT EXISTS users (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username   VARCHAR(100)              NOT NULL,
    email      VARCHAR(255)              NOT NULL,
    password   VARCHAR(255)              NOT NULL,
    role       VARCHAR(20)               NOT NULL DEFAULT 'READER',
    created_at TIMESTAMP                 NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP                 NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_users           PRIMARY KEY (id),
    CONSTRAINT uq_users_email     UNIQUE (email),
    CONSTRAINT uq_users_username  UNIQUE (username),
    CONSTRAINT chk_user_role      CHECK (role IN ('ADMIN', 'READER'))
);

-- 2. categories
CREATE TABLE IF NOT EXISTS categories (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(100) NOT NULL,
    slug        VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_categories      PRIMARY KEY (id),
    CONSTRAINT uq_categories_slug UNIQUE (slug),
    CONSTRAINT uq_categories_name UNIQUE (name)
);

-- 3. posts
CREATE TABLE IF NOT EXISTS posts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title           VARCHAR(500)                 NOT NULL,
    slug            VARCHAR(255)                 NOT NULL,
    summary         TEXT,
    content         TEXT                         NOT NULL,
    cover_image_url VARCHAR(500),
    status          VARCHAR(20)                  NOT NULL DEFAULT 'DRAFT',
    author_id       BIGINT                       NOT NULL,
    published_at    TIMESTAMP,
    created_at      TIMESTAMP                    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP                    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_posts        PRIMARY KEY (id),
    CONSTRAINT uq_posts_slug   UNIQUE (slug),
    CONSTRAINT fk_posts_author FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT chk_post_status CHECK (status IN ('DRAFT', 'PUBLISHED'))
);

CREATE INDEX idx_posts_status       ON posts (status);
CREATE INDEX idx_posts_author_id    ON posts (author_id);
CREATE INDEX idx_posts_published_at ON posts (published_at);

-- 4. tags
CREATE TABLE IF NOT EXISTS tags (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name       VARCHAR(100) NOT NULL,
    slug       VARCHAR(100) NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_tags      PRIMARY KEY (id),
    CONSTRAINT uq_tags_slug UNIQUE (slug),
    CONSTRAINT uq_tags_name UNIQUE (name)
);

-- 5. post_categories
CREATE TABLE IF NOT EXISTS post_categories (
    post_id     BIGINT NOT NULL,
    category_id BIGINT NOT NULL,

    CONSTRAINT pk_post_categories PRIMARY KEY (post_id, category_id),
    CONSTRAINT fk_pc_post         FOREIGN KEY (post_id)     REFERENCES posts(id)      ON DELETE CASCADE,
    CONSTRAINT fk_pc_category     FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE
);

-- 6. post_tags
CREATE TABLE IF NOT EXISTS post_tags (
    post_id BIGINT NOT NULL,
    tag_id  BIGINT NOT NULL,

    CONSTRAINT pk_post_tags PRIMARY KEY (post_id, tag_id),
    CONSTRAINT fk_pt_post   FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
    CONSTRAINT fk_pt_tag    FOREIGN KEY (tag_id)  REFERENCES tags(id)  ON DELETE CASCADE
);

-- 7. comments
CREATE TABLE IF NOT EXISTS comments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    post_id     BIGINT       NOT NULL,
    author_name VARCHAR(100) NOT NULL,
    email       VARCHAR(255) NOT NULL,
    body        TEXT         NOT NULL,
    approved    BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_comments      PRIMARY KEY (id),
    CONSTRAINT fk_comments_post FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE CASCADE
);

CREATE INDEX idx_comments_post_id  ON comments (post_id);
CREATE INDEX idx_comments_approved ON comments (approved);
